# Generated by Django 5.2.7 on 2025-11-02 12:59

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[\\w.+-]+$',
                        code='invalid_username',
                        message='Enter a valid username. This value may contain only letters, numbers, and ./+/-/_ characters.',
                    )
                ],
                verbose_name='username',
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('username'),
                name='unique_lower_username',
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('email'),
                name='unique_lower_email',
            ),
        ),
    ]
