# Generated by Django 5.2.7 on 2025-11-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='user',
            new_name='users',
        ),
    ]
