# Generated by Django 5.2.7 on 2025-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_user_location_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_latitude_longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='geo_key',
            field=models.CharField(db_index=True, default='1', max_length=64, unique=True, verbose_name='geo_key'),
            preserve_default=False,
        ),
    ]
