# Generated by Django 5.2.7 on 2025-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_location_unique_latitude_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geo_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='geo_key'),
        ),
    ]
